name: Deploy to WordPress.org
on:
  push:
    tags:
    - "*"
jobs:
  tag:
    name: Wordpress release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Wordpress plugin deploy
        uses: 10up/action-wordpress/dotorg-plugin-deploy@stable
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}  
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}  
